This is makeindex, version 2.15 [TeX Live 2019] (kpathsea + Thai support).
Scanning style file ./project_proposal.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file project_proposal.acn....done (52 entries accepted, 0 rejected).
Sorting entries....done (305 comparisons).
Generating output file project_proposal.acr....done (36 lines written, 0 warnings).
Output written in project_proposal.acr.
Transcript written in project_proposal.alg.
