This is makeindex, version 2.15 [TeX Live 2019] (kpathsea + Thai support).
Scanning style file ./project_writeup.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file project_writeup.acn....done (4 entries accepted, 0 rejected).
Sorting entries....done (9 comparisons).
Generating output file project_writeup.acr....done (6 lines written, 0 warnings).
Output written in project_writeup.acr.
Transcript written in project_writeup.alg.
